name: travely
description: A travel service to find your next destination

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0 # Core de firebase.
  firebase_database: ^6.0.0 # Per la real time database -> guardar bookins preferits
  firebase_auth: ^0.20.0+1 # Per auth dels usuaris
  cupertino_icons: ^1.0.0 # Iconos de IOS
  equatable: ^1.1.1 # Permet comprar objectes
  video_player: ^1.0.1 #Lowlevel video player
  chewie: ^0.12.2 # Abstract del video_player.
  flutter_cache_manager: ^1.2.2 #Cache manager per als videos.
  pedantic: ^1.8.0+1 # Revisa que el codi compleixi amb best practices de google
  http: ^0.12.2 # Per a les peticions a les apis.
  google_maps_flutter: ^1.1.1 # Per el mapa de preus
  google_place: ^0.3.3
  google_fonts: ^1.1.2 # Per fonts de google.
  geolocator: ^6.1.14 # Per localitzacio del usuari
  provider: ^4.3.3 # Per state management
  intl: ^0.16.1 # Per date fromat
  flutter_spinkit: ^4.1.2+1 #Loading icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_staggered_grid_view:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/logo.png
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
